// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLPKQGC-QRNqjj0XBJoRuN3XF6TFikOVM',
    appId: '1:8296393356:ios:019827aa58193f850d69a9',
    messagingSenderId: '8296393356',
    projectId: 'movekigali-9d268',
    storageBucket: 'movekigali-9d268.firebasestorage.app',
    iosBundleId: 'com.example.movvekigaliFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLPKQGC-QRNqjj0XBJoRuN3XF6TFikOVM',
    appId: '1:8296393356:ios:019827aa58193f850d69a9',
    messagingSenderId: '8296393356',
    projectId: 'movekigali-9d268',
    storageBucket: 'movekigali-9d268.firebasestorage.app',
    iosBundleId: 'com.example.movvekigaliFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD90O8ZzJrSDKrv6u8sgbZ4iyTzYAvhENk',
    appId: '1:8296393356:web:96c586cd4207d6ae0d69a9',
    messagingSenderId: '8296393356',
    projectId: 'movekigali-9d268',
    authDomain: 'movekigali-9d268.firebaseapp.com',
    storageBucket: 'movekigali-9d268.firebasestorage.app',
    measurementId: 'G-NJRGHRZ6HM',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD90O8ZzJrSDKrv6u8sgbZ4iyTzYAvhENk',
    appId: '1:8296393356:web:96c586cd4207d6ae0d69a9',
    messagingSenderId: '8296393356',
    projectId: 'movekigali-9d268',
    authDomain: 'movekigali-9d268.firebaseapp.com',
    storageBucket: 'movekigali-9d268.firebasestorage.app',
    measurementId: 'G-NJRGHRZ6HM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC97BF31u9Hl6iSp7IvY462CWzTMZYZC0I',
    appId: '1:8296393356:android:d33c7c2ee99110e30d69a9',
    messagingSenderId: '8296393356',
    projectId: 'movekigali-9d268',
    storageBucket: 'movekigali-9d268.firebasestorage.app',
  );

}