// Simple built-in translations for moveKigali.

const List<Map<String, String>> supportedLanguages = [
  {'code': 'rw', 'name': 'Kinyarwanda', 'flag': '🇷🇼'},
  {'code': 'sw', 'name': 'Swahili',     'flag': '🇰🇪'},
  {'code': 'en', 'name': 'English',     'flag': '🇺🇸'},
  {'code': 'fr', 'name': 'French',      'flag': '🇫🇷'},
];

const Map<String, Map<String, String>> _translations = {
  'en': {
    'home': 'Home',
    'safe_travel': 'Safe and comfortable travel to your destination',
    'search_ticket': 'Search Ticket',
    'departure': 'Departure',
    'destination': 'Destination',
    'select_departure': 'Select departure',
    'select_destination': 'Select destination',
    'select_passengers': 'Select passengers',
    'select_travel_date': 'Select travel date',
    'passengers': 'Passengers',
    'buspoints': 'Buspoints',
    'your_buspoints': 'Your buspoints',
    'history': 'History',
    'recent_trips': 'Recent trips',
    'no_trips': 'No trips yet. Book a ticket to see them here.',
    'download': 'Download',
    'view_route': 'View Route',
    'ticket_issued': 'Ticket Issued',
    'paid_via': 'Paid via',
    'total_price': 'Total Price',
    'view_all': 'View All',
    'change_selections': 'Change Selections',
    'ticket_details': 'Ticket Details',
    'ticket_details_hint': 'Show this ticket to your conductor for boarding verification.',
    'transaction': 'Transaction',
    'route': 'Route',
    'payment': 'Payment',
    'amount_paid': 'Amount Paid',
    'share_ticket': 'Share Ticket',
    'no_completed_tickets': 'No completed tickets yet. Book a ticket to make it available here.',
    'completed_tickets': 'Completed Tickets',
    'no_trips_headline': 'No trips yet',
    'no_trips_subtitle': 'Your booked tickets will appear here.\nSearch and book your first trip above!',
    'date': 'Date',
    'payment_method': 'Payment Method',
    'how_to_pay': 'How would you like to pay?',
    'language_title': 'Choose Language',
    'language_subtitle': 'Select the language you want to use in the app.',
    'close': 'Close',
    'pay_now': 'Pay Now',
    'book_ticket': 'Book Ticket',
    'buy_ticket': 'Buy Ticket',
    'summary': 'Summary',
    'complete_form': 'Complete the form below to purchase moveKigali tickets',
    'travel_date': 'Travel Date',
    'redeem': 'Redeem',
    'please_select_a_departure_point': 'Please select a departure point',
    'please_select_a_destination': 'Please select a destination',
    'depart_same_warning': 'Departure and destination cannot be the same',
    'please_select_a_travel_date': 'Please select a travel date',
    'search_again': 'Search Again',
    'detail': 'Detail',
    'vehicle_type': 'Vehicle Type',
    'bus_number': 'Bus Number',
    'route_type': 'Route Type',
    'search_passengers': 'Search passengers',
    'passenger': 'Passenger',
    'seats_available': 'Seats Available',
    'seats': 'Seats',
    'change': 'Change',
    'available_at_checkout': '{method} is available at checkout.',
    'estimated_travel_duration': 'The travel duration is an estimated time that may change depending on traffic conditions.',
    'complete_card_fields': 'Please complete all card fields correctly.',
    'enter_card_details': 'Enter your card details to complete payment securely.',
    'cardholder_name': 'Cardholder Name',
    'enter_name_on_card': 'Enter the name on Card',
    'card_number': 'Card Number',
    'enter_card_number': 'Enter the card number',
    'expiry_date': 'Expiry Date',
    'expiry_format': 'MM/YY',
    'cvv': 'CVV',
    'pay_with': 'Pay with {card}',
    'no_stations_found': 'No stations found',
    'payment_methods_description': 'Select how you would like to pay for your ticket.',
    'order_information': 'Order Information',
    'passenger_information': 'Passenger Information',
    'select_member_name': 'Select Member Name',
    'phone_number': 'Phone Number',
    'ticket_sent_notification': 'The ticket will be sent to the number above, please ensure the passenger\'s WhatsApp number is correct.',
    'agree_terms': 'I agree to the moveKigali Terms & Conditions and the Privacy Policy',
    'moveKigali_ticket': 'moveKigali ticket',
    'continue': 'Continue',
    'sign_in_to_movekigali': 'Injira na moveKigali Account',
    'enter_your_email_or_phone': 'Enter your email or phone and password to continue.',
    'secure_sign_in_message': 'Secure sign-in for Rwanda travel. We keep your data safe and private.',
    'remember_me': 'Remember me',
    'forgot_password': 'Forgot Password?',
    'by_logging_in_terms': 'By logging in, you accept moveKigali Terms & Conditions and Privacy Policy.',
    'sign_in': 'Sign In',
    'login': 'Login',
    'register': 'Register',
    'sign_up': 'Sign Up',
    'create_account_prompt': 'Create an account to continue',
    'enter_valid_email': 'Enter a valid email address',
    'onboarding_skip': 'Skip',
    'onboarding_title_1': 'Buy your bus ticket from anywhere',
    'onboarding_subtitle_1': 'Use moveKigali to purchase your ticket quickly and safely wherever you are.',
    'onboarding_start': 'Start',
    'onboarding_title_2': 'Track your journey in real time.',
    'onboarding_subtitle_2': 'See where you are and what to expect next on your trip. Never miss your stop again.',
    'onboarding_continue': 'Continue',
    'full_name': 'Full Name',
    'email_address': 'Email Address',
    'confirm_password': 'Confirm Password',
    'dont_have_account': 'Don\'t have an account?',
    'please_fill_all_fields': 'Please fill in all fields above.',
    'please_accept_terms': 'Please accept Terms & Conditions before continuing.',
    'passwords_do_not_match': 'Passwords don\'t match',
    'enter_valid_phone': 'Enter a valid 9-digit phone number',
    'create_account_success': 'Account created successfully! Please check your email for verification.',
    'login_again': 'Login',
    'select_payment_method': 'Select Payment Method',
    'payment_methods': 'Payment Methods',
    'payment_and_pricing_information': 'Payment and Pricing Information',
    'need_more_points': 'Need {points} more points for this trip. You have {balance} pts.',
    'buspoint_balance': 'Buspoint Balance',
    'not_eligible': 'Not eligible',
    'total_ticket': 'Total Ticket',
    'please_select_payment_method': 'Please select a payment method',
    'mobile_money': 'Mobile Money',
    'qr_scanner': 'QR Scanner',
    'help_center': 'Help Center',
    'page_under_construction': 'This page is under construction. Replace with your own content.',
    'service_fee': 'Service Fee',
    'voucher': 'Voucher',
    'buspoint_discount': 'Buspoint Discount',
    'total_cost': 'Total Cost',
    'payment_method_title': 'Payment Method',
    'how_would_you_like_to_pay': 'How Would You Like to Pay?',
    'confirm': 'Confirm',
    'airtel_money': 'Airtel Money',
    'mtn_mobile_money': 'MTN Mobile Money',
    'digital_banking': 'Digital Banking',
    'debit_credit_card': 'Debit/Credit Card',
    'pay_via_airtel_money': 'Pay via Airtel Money',
    'pay_via_digital_banking': 'Pay via Digital Banking',
    'enter_airtel_account_number': 'Enter your Airtel Money number',
    'enter_mtn_account_number': 'Enter your MTN Mobile Money number',
    'after_pay_prompt': 'After you press pay, you will be prompted to submit your Mobile Money PIN on your phone to complete the payment.',
    'select_country': 'Select Country',
    'save': 'Save',
    'moveKigali_description': 'moveKigali is Rwanda’s digital bus travel platform for safe and reliable intercity transport.',
    'moveKigali_connects': 'moveKigali connects passengers with Rwanda’s registered bus operators, allowing travelers to book seats, view schedules, and manage trips across Kigali and national routes.',
    'why_choose_movekigali_point_1': 'Secure ticket booking for Rwanda bus travel, including local and intercity routes.',
    'why_choose_movekigali_point_2': 'Clear fare details, seat selections, and digital ticket storage in the app.',
    'why_choose_movekigali_point_3': 'Built for Rwanda’s public transport ecosystem with customer safety and convenience in mind.',
    'our_commitment_description': 'We support Rwanda’s bus transport corridor by making ticketing faster, more transparent, and easier to access for every traveler.',
    'terms_intro': 'These terms govern the use of moveKigali for Rwanda bus ticket booking and transport services.',
    'service_scope_text': 'moveKigali is a booking platform connecting passengers with registered Rwanda bus operators. It is not itself a bus operator, and travel is subject to the policies of the chosen carrier.',
    'booking_rule_1': 'Tickets are confirmed only after payment and are subject to seat availability.',
    'booking_rule_2': 'Passengers must provide accurate personal information and valid identity when boarding.',
    'booking_rule_3': 'Changes, cancellations, and refunds follow the bus operator’s terms and Rwanda transport regulations.',
    'traveler_responsibility_1': 'Use the app responsibly and do not share or resell tickets to unauthorized parties.',
    'traveler_responsibility_2': 'Follow safety instructions, luggage rules, and boarding times provided by the operator.',
    'disclaimer_text': 'moveKigali provides the service as a convenience platform. We aim for accurate schedules and pricing, but final travel details are controlled by the bus operator and may change. Users accept responsibility for verifying departure details before travel.',
    'book_tickets': 'Book {count} Tickets',
    'member': 'Member',
    'non_member': 'Non-member',
    'bus_type': 'Bus Type',
    'arrival': 'Arrival',
    'from': 'From',
    'duration': 'Duration',
    'yes_sure': 'Yes, Sure',
    'available_buspoints': 'Available: {count} Buspoints',
    'redeem_prompt': 'Redeem {cost} Buspoints for\nGOGOBUS Coffee Latte?',
    'redeem_reward_title': 'GOGOBUS Coffee Latte',
    'redeem_cost': '{cost} Buspoint',
    'unavailable': 'Unavailable',
    'today': 'Today',
    'selected': 'Selected',
    'save_date': 'Save Date',
    'select_departure_date': 'Select Departure Date',
    'trip_activity': 'Trip Activity',
    'live_map': 'Live Map',
    'about_movekigali': 'About moveKigali',
    'terms_conditions': 'Terms & Conditions',
    'what_we_do': 'What we do',
    'why_choose_movekigali': 'Why choose moveKigali?',
    'our_commitment': 'Our commitment',
    'service_scope': 'Service scope',
    'booking_rules': 'Booking rules',
    'traveler_responsibilities': 'Traveler responsibilities',
    'disclaimer': 'Disclaimer',
    'schedule_available': 'Schedule Available',
    'plug_in_google_maps_here': 'Plug in Google Maps here',
    'e_ticket': 'e-Ticket',
    'name': 'Name',
    'whatsapp_number': 'WhatsApp Number',
    'transaction_date': 'Transaction Date',
    'transaction_time': 'Transaction Time',
    'show_qr_instruction': 'Show this QR code at boarding',
    'failed_save_ticket': 'Failed to save ticket: {error}',
    'ticket_download_started': 'Ticket download started',
    'ticket_saved_to': 'Ticket saved to {path}',
    'facilities': 'Facilities',
    'meal_service': 'Meal Service',
    'snack_only': 'Snack Only',
  },
  'rw': {
    'home': 'Ahabanza',
    'safe_travel': 'Tukwifurije urugendo rwiza kandi rutekanye rugana aho ujya',
    'search_ticket': 'Shaka itike',
    'departure': 'Gutanga',
    'destination': 'Uruhare',
    'select_departure': 'Hitamo aho utangirira',
    'select_destination': 'Hitamo aho ugera',
    'select_passengers': 'Hitamo abagenzi',
    'select_travel_date': 'Hitamo itariki y\'urugendo',
    'passengers': 'Abagenzi',
    'buspoints': 'Inota za Bus',
    'your_buspoints': 'Inota zawe za Bus',
    'history': 'Amateka',
    'recent_trips': 'Ingendo za vuba',
    'no_trips': 'Nta ngendo zigaragara. Tega itike ubone uboneze aha.',
    'download': 'Kuramo',
    'view_route': 'Reba inzira',
    'ticket_issued': 'Itike yashyizweho',
    'paid_via': 'Yishyuye kuri',
    'total_price': 'Igiciro rusange',
    'bus_number': 'Numero ya Bus',
    'route_type': 'Ubwoko bw’inzira',
    'search_passengers': 'Shakisha abagenzi',
    'passenger': 'Umugenzi',
    'seats': 'Intebe',
    'change': 'Hindura',
    'available_at_checkout': '{method} biraboneka kuri checkout.',
    'estimated_travel_duration': 'Igihe cy’urugendo ni igipimo gishobora guhinduka bitewe n’oguhura n’umuhanda.',
    'complete_card_fields': 'Wuzuza neza imirima yose y’ikadi.',
    'enter_card_details': 'Andika amakuru y’ikarita yawe kugira ngo ubone kwishyura neza.',
    'cardholder_name': 'Izina ry’umufite ikarita',
    'enter_name_on_card': 'Andika izina riri kuri ikarita',
    'card_number': 'Numero y’ikarita',
    'enter_card_number': 'Andika numero y’ikarita',
    'expiry_date': 'Igihe isohoka',
    'expiry_format': 'MM/YY',
    'cvv': 'CVV',
    'pay_with': 'Wishyure na {card}',
    'no_stations_found': 'Nta mashuri yabonetse',
    'payment_methods_description': 'Hitamo uburyo ushaka kwishyura itike yawe.',
    'order_information': 'Amakuru y’urugendo',
    'passenger_information': 'Amakuru y’umugenzi',
    'transaction_date': 'Itariki y’iyakureba',
    'transaction_time': 'Igihe cy’iyakureba',
    'view_all': 'Reba byose',
    'change_selections': 'Hindura amahitamo',
    'ticket_details': 'Amakuru y’itike',
    'ticket_details_hint': 'Erekana iyi tike umuvugizi wawe kugira ngo yemezwe.',
    'transaction': 'Urugendo',
    'route': 'Umuhanda',
    'payment': 'Uburyo bwo kwishyura',
    'amount_paid': 'Amafaranga yishyuwe',
    'share_ticket': 'Sangira itike',
    'no_completed_tickets': 'Nta matike yarangije kuboneka. Tega itike kugira ngo iboneke hano.',
    'completed_tickets': 'Amatike yarangije',
    'no_trips_headline': 'Nta ngendo',
    'no_trips_subtitle': 'Amatike wakiriye azagaragara hano. Shaka kandi utegure urugendo rwa mbere hejuru!',
    'date': 'Itariki',
    'payment_method': 'Uburyo bwo kwishyura',
    'how_to_pay': 'Ushaka kwishyura ute?',
    'language_title': 'Hitamo ururimi',
    'language_subtitle': 'Hitamo ururimi ushaka gukoresha mu app.',
    'close': 'Funga',
    'pay_now': 'Hindura ubu',
    'book_ticket': 'Tega itike',
    'buy_ticket': 'Gura itike',
    'summary': 'Isuzuma',
    'sign_in_to_movekigali': 'Injira na moveKigali Account',
    'enter_your_email_or_phone': 'Andika amakuru yawe kugira ngo ukomeze kuri moveKigali Account.',
    'secure_sign_in_message': 'Injira mu buryo butekanye kuri Rwanda. Turakingira amakuru yawe.',
    'remember_me': 'Nkurikiza',
    'forgot_password': 'Wibagiwe ijambo ry\'ibanga?',
    'by_logging_in_terms': 'Mu kwinjira, wemera Amategeko agenga imikorere harimo na Politiki y\'ibanga ya moveKigali Account.',
    'sign_in': 'Injira',
    'login': 'Injira',
    'register': 'Fungura konti',
    'sign_up': 'Fungura konti',
    'create_account_prompt': 'Fungura konti yawe ya moveKigali',
    'full_name': 'Amazina yawe yose',
    'email_address': 'Andika aderesi ya email',
    'confirm_password': 'Subiramo ijambo ry’ibanga',
    'dont_have_account': 'Nta konti ufite?',
    'phone_number': 'Andika numero yawe ya telefone',
    'password': 'Ijambo ry\'ibanga',
    'email': 'Email',
    'phone': 'Telefone',
    'login_intro': 'Kugeza aho ugana neza ni inshingano yacu kandi ni umutekano w’abagenzi bose.',
    'password_guidelines': 'Koresha inyuguti 8+ n\'inyuguti nini, nto, imibare n\'ibimenyetso.',
    'already_have_account': 'Usanzwe ufite konti?',
    'agree_terms': 'Nemera Amabwiriza na Politiki ya moveKigali.',
    'onboarding_skip': 'Taruka',
    'onboarding_title_1': 'Gura itike ya bus aho uri hose',
    'onboarding_subtitle_1': 'Gura itike yawe ukoresheje MoveKigali, uyigezweho aho utuye.',
    'onboarding_start': 'Tangira',
    'onboarding_title_2': 'Kurikirana urugendo rwawe mu gihe nyacyo.',
    'onboarding_subtitle_2': 'Menya aho ugeze n\'imiterere y\'urugendo rwawe. Ntuzongera kurenga cyangwa kubura aho ugomba kugera.',
    'onboarding_continue': 'Komeza',
  },
  'fr': {
    'home': 'Accueil',
    'safe_travel': 'Voyage sûr et confortable vers votre destination',
    'search_ticket': 'Rechercher un billet',
    'departure': 'Départ',
    'destination': 'Destination',
    'select_departure': 'Choisir le départ',
    'select_destination': 'Choisir la destination',
    'select_passengers': 'Choisir les passagers',
    'select_travel_date': 'Choisir la date de voyage',
    'passengers': 'Passagers',
    'buspoints': 'Buspoints',
    'your_buspoints': 'Vos Buspoints',
    'history': 'Historique',
    'recent_trips': 'Voyages récents',
    'no_trips': 'Aucun voyage pour le moment. Réservez un billet pour les voir ici.',
    'download': 'Télécharger',
    'view_route': 'Voir l’itinéraire',
    'ticket_issued': 'Billet émis',
    'paid_via': 'Payé via',
    'total_price': 'Prix total',
    'payment_method': 'Méthode de paiement',
    'how_to_pay': 'Comment souhaitez-vous payer?',
    'language_title': 'Choisir la langue',
    'language_subtitle': 'Sélectionnez la langue à utiliser dans l’application.',
    'sign_in_to_movekigali': 'Connectez-vous à moveKigali Account',
    'enter_your_email_or_phone': 'Entrez votre téléphone ou email et mot de passe pour continuer.',
    'remember_me': 'Se souvenir de moi',
    'forgot_password': 'Mot de passe oublié?',
    'by_logging_in_terms': 'En vous connectant, vous acceptez les conditions d\'utilisation et la politique de confidentialité de moveKigali.',
    'sign_in': 'Se connecter',
    'login': 'Se connecter',
    'onboarding_skip': 'Passer',
    'onboarding_title_1': 'Achetez votre billet de bus de n\'importe où',
    'onboarding_subtitle_1': 'Utilisez moveKigali pour acheter votre billet rapidement et en toute sécurité où que vous soyez.',
    'onboarding_start': 'Démarrer',
    'onboarding_title_2': 'Suivez votre trajet en temps réel.',
    'onboarding_subtitle_2': 'Voyez où vous êtes et ce qui vous attend ensuite lors de votre voyage. Ne manquez plus jamais votre arrêt.',
    'onboarding_continue': 'Continuer',
    'email_address': 'Adresse e-mail',
    'phone_number': 'Numéro de téléphone',
    'email': 'Email',
    'phone': 'Téléphone',
    'password': 'Mot de passe',
    'close': 'Fermer',
    'pay_now': 'Payer maintenant',
    'book_ticket': 'Réserver un billet',
    'buy_ticket': 'Acheter un billet',
    'summary': 'Résumé',
  },
  'sw': {
    'home': 'Nyumbani',
    'safe_travel': 'Safari salama na ya furaha hadi mahali ulipoenda',
    'search_ticket': 'Tafuta tiketi',
    'departure': 'Kuondoka',
    'destination': 'Mwenendo',
    'select_departure': 'Chagua kuondoka',
    'select_destination': 'Chagua mwisho',
    'select_passengers': 'Chagua abageni',
    'select_travel_date': 'Chagua tarehe ya safari',
    'passengers': 'Abageni',
    'buspoints': 'Buspoints',
    'your_buspoints': 'Buspoints zako',
    'history': 'Historia',
    'recent_trips': 'Safari za hivi karibuni',
    'no_trips': 'Hakuna safari kwa sasa. Nunua tiketi ili ukaone hapa.',
    'download': 'Pakua',
    'view_route': 'Angalia njia',
    'ticket_issued': 'Tiketi imetolewa',
    'paid_via': 'Imelipwa kwa',
    'total_price': 'Bei jumla',
    'payment_method': 'Njia ya malipo',
    'how_to_pay': 'Ungependa kulipa vipi?',
    'language_title': 'Chagua lugha',
    'language_subtitle': 'Chagua lugha unayotaka kutumia katika app.',
    'enter_valid_email': 'Andika aderesi ya email ikwiye',
    'onboarding_skip': 'Ruka',
    'onboarding_title_1': 'Nunua tiketi ya basi kutoka mahali popote',
    'onboarding_subtitle_1': 'Tumia moveKigali kununua tiketi yako kwa haraka na kwa usalama popote ulipo.',
    'onboarding_start': 'Anza',
    'onboarding_title_2': 'Fuata safari yako kwa wakati halisi.',
    'onboarding_subtitle_2': 'Angalia uko wapi na unachotarajia katika safari yako. Usikose kitu tena.',
    'onboarding_continue': 'Endelea',
    'close': 'Funga',
    'pay_now': 'Lipa sasa',
    'book_ticket': 'Nunua tiketi',
    'buy_ticket': 'Nunua tiketi',
    'summary': 'Muhtasari',
  },
  'pt': {
    'home': 'Início',
    'safe_travel': 'Viagem segura e confortável para o seu destino',
    'search_ticket': 'Buscar passagem',
    'departure': 'Partida',
    'destination': 'Destino',
    'select_departure': 'Escolha partida',
    'select_destination': 'Escolha destino',
    'select_passengers': 'Escolha passageiros',
    'select_travel_date': 'Escolha data de viagem',
    'passengers': 'Passageiros',
    'buspoints': 'Buspoints',
    'your_buspoints': 'Seus Buspoints',
    'history': 'Histórico',
    'recent_trips': 'Viagens recentes',
    'no_trips': 'Nenhuma viagem ainda. Reserve uma passagem para ver aqui.',
    'download': 'Baixar',
    'view_route': 'Ver rota',
    'ticket_issued': 'Bilhete emitido',
    'paid_via': 'Pago via',
    'total_price': 'Preço total',
    'payment_method': 'Forma de pagamento',
    'how_to_pay': 'Como você deseja pagar?',
    'language_title': 'Escolher idioma',
    'language_subtitle': 'Selecione o idioma que deseja usar no app.',
    'close': 'Fechar',
    'pay_now': 'Pagar agora',
    'book_ticket': 'Reservar passagem',
    'buy_ticket': 'Comprar passagem',
    'summary': 'Resumo',
  },
  'ar': {
    'home': 'الرئيسية',
    'safe_travel': 'سفر آمن ومريح إلى وجهتك',
    'search_ticket': 'ابحث عن تذكرة',
    'departure': 'المغادرة',
    'destination': 'الوصول',
    'select_departure': 'اختر نقطة الانطلاق',
    'select_destination': 'اختر الوجهة',
    'select_passengers': 'اختر عدد الركاب',
    'select_travel_date': 'اختر تاريخ السفر',
    'passengers': 'الركاب',
    'buspoints': 'نقاط الباص',
    'your_buspoints': 'نقاطك',
    'history': 'السجل',
    'recent_trips': 'الرحلات الأخيرة',
    'no_trips': 'لا توجد رحلات بعد. احجز تذكرة لرؤيتها هنا.',
    'download': 'تنزيل',
    'view_route': 'عرض المسار',
    'ticket_issued': 'تم إصدار التذكرة',
    'paid_via': 'دفع عبر',
    'total_price': 'السعر الكلي',
    'payment_method': 'طريقة الدفع',
    'how_to_pay': 'كيف تريد الدفع؟',
    'language_title': 'اختر اللغة',
    'language_subtitle': 'اختر اللغة التي تريد استخدامها في التطبيق.',
    'close': 'إغلاق',
    'pay_now': 'ادفع الآن',
    'book_ticket': 'احجز تذكرة',
    'buy_ticket': 'شراء تذكرة',
    'summary': 'الملخص',
  },
  'zh': {
    'home': '首页',
    'safe_travel': '安全舒适地前往您的目的地',
    'search_ticket': '搜索车票',
    'departure': '出发',
    'destination': '目的地',
    'select_departure': '选择出发地',
    'select_destination': '选择目的地',
    'select_passengers': '选择乘客',
    'select_travel_date': '选择旅行日期',
    'passengers': '乘客',
    'buspoints': 'Buspoints',
    'your_buspoints': '您的Buspoints',
    'history': '历史',
    'recent_trips': '最近行程',
    'no_trips': '还没有行程。预订车票后将在此显示。',
    'download': '下载',
    'view_route': '查看路线',
    'ticket_issued': '车票已出票',
    'paid_via': '支付方式',
    'total_price': '总价',
    'payment_method': '付款方式',
    'how_to_pay': '您想如何付款？',
    'language_title': '选择语言',
    'language_subtitle': '选择您想在应用中使用的语言。',
    'close': '关闭',
    'pay_now': '立即支付',
    'book_ticket': '预订车票',
    'buy_ticket': '购买车票',
    'summary': '摘要',
  },
  'es': {
    'home': 'Inicio',
    'safe_travel': 'Viaje seguro y cómodo a su destino',
    'search_ticket': 'Buscar boleto',
    'departure': 'Salida',
    'destination': 'Destino',
    'select_departure': 'Seleccionar salida',
    'select_destination': 'Seleccionar destino',
    'select_passengers': 'Seleccionar pasajeros',
    'select_travel_date': 'Seleccionar fecha de viaje',
    'passengers': 'Pasajeros',
    'buspoints': 'Buspoints',
    'your_buspoints': 'Tus Buspoints',
    'history': 'Historial',
    'recent_trips': 'Viajes recientes',
    'no_trips': 'Aún no hay viajes. Reserva un boleto para verlos aquí.',
    'download': 'Descargar',
    'view_route': 'Ver ruta',
    'ticket_issued': 'Boleto emitido',
    'paid_via': 'Pagado vía',
    'total_price': 'Precio total',
    'payment_method': 'Método de pago',
    'how_to_pay': '¿Cómo te gustaría pagar?',
    'language_title': 'Elegir idioma',
    'language_subtitle': 'Seleccione el idioma que desea usar en la aplicación.',
    'close': 'Cerrar',
    'pay_now': 'Pagar ahora',
    'book_ticket': 'Reservar boleto',
    'buy_ticket': 'Comprar boleto',
    'summary': 'Resumen',
  },
};

String translate(String key, String code) {
  if (!_translations.containsKey(code)) code = 'en';
  return _translations[code]?[key] ?? _translations['en']?[key] ?? key;
}

String languageName(String code) {
  final lang = supportedLanguages.firstWhere(
    (item) => item['code'] == code,
    orElse: () => supportedLanguages.first,
  );
  return lang['name']!;
}
